=== SailorBLR/4_XML_Hubarevich_XMLParser/resources/travel-vouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.hubarevich.by/tourist-vouchers"
        xmlns:tns="http://www.hubarevich.by/tourist-vouchers"
        elementFormDefault="qualified">

    <element name="tourist-vouchers">
        <complexType>
            <sequence>
                <element ref="tns:voucher"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>


    <element name="voucher" type="tns:common-voucher" abstract="true"></element>
    <element name="international-voucher" type="tns:foreign-voucher" substitutionGroup="tns:voucher"></element>
    <element name="national-voucher" type="tns:local-voucher" substitutionGroup="tns:voucher"></element>


    <complexType name="hotel-type">
        <sequence>
            <element type="string" name="city"/>
            <element name="type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Hotel"/>
                        <enumeration value="Village_house"/>
                        <enumeration value="Hostel"/>
                        <enumeration value="no"/>
                        <enumeration value="Desert/"/>
                    </restriction>
                </simpleType>
            </element>
            <element type="string" name="name">
            </element>
            <element name="stars">
                <simpleType>
                    <restriction base="short">
                        <enumeration value="2"/>
                        <enumeration value="3"/>
                        <enumeration value="5"/>
                        <enumeration value="0"/>
                        <enumeration value="4"/>
                        <enumeration value="1"/>
                        <enumeration value="1001"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="food">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="BB"/>
                        <enumeration value="FB"/>
                        <enumeration value="RO"/>
                        <enumeration value="HB"/>
                        <enumeration value="AI"/>
                        <enumeration value="UAI"/>
                        <enumeration value="HB+"/>
                        <enumeration value="FB+"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="tv-equipe">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="true"/>
                        <enumeration value="false"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="air-condition">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="false"/>
                        <enumeration value="true"/>
                    </restriction>
                </simpleType>
            </element>
            <element type="positiveInteger" name="persons"/>
            <element name="elevator">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="floor"/>
                        <enumeration value="no"/>
                        <enumeration value="penthouse"/>
                        <enumeration value="camel"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <simpleType name="identification">
        <restriction base="int">
            <pattern value="[0-9]+"/>
        </restriction>
    </simpleType>

    <simpleType name="days-nights">
        <restriction base="string">
            <pattern value="[0-9]{1,2}.[0-9]{1,2}"/>
        </restriction>
    </simpleType>


    <!--Available voucher types-->
    <complexType name="common-voucher">

        <sequence>
            <element name="voucher-type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="holiday_tour"/>
                        <enumeration value="excursion"/>
                        <enumeration value="recreation"/>
                        <enumeration value="shop_tour"/>
                        <enumeration value="ride"/>
                        <enumeration value="hegira"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="number-days-nights" type="tns:days-nights"/>
            <element name="transfer">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="bus"/>
                        <enumeration value="airplane"/>
                        <enumeration value="train"/>
                        <enumeration value="ship"/>
                        <enumeration value="car"/>
                        <enumeration value="motorcycle"/>
                        <enumeration value="pedestrian"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="hotel" type="tns:hotel-type"/>
            <element type="float" name="cost"/>
        </sequence>
        <attribute name="id" type="tns:identification" use="required"/>

    </complexType>

    <complexType name="foreign-voucher">
        <complexContent>
            <extension base="tns:common-voucher">
                <attribute name="country" type="string" use="required"/>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="local-voucher">
        <complexContent>
            <extension base="tns:common-voucher">
                <sequence>
                    <element name="professional-union" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

</schema>

=== SailorBLR/4_XML_Hubarevich_XMLParser/resources/travel-vouchers.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>


<!--The list of tour vouchers-->
<tourist-vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns="http://www.hubarevich.by/tourist-vouchers"
                  xsi:schemaLocation="http://www.hubarevich.by/tourist-vouchers travel-vouchers.xsd">


    <!--Country of visit. In case of multicountry trip:
        The first country of visit-->
    <international-voucher id="1001" country="Russian_Federation">
        <!-- Tour type according to staying days-->
        <voucher-type>holiday_tour</voucher-type>
        <!--Days/nights of staying-->
        <number-days-nights>2/1</number-days-nights>
        <!--Transfer type (bus,train,plain)-->
        <transfer>train</transfer>
        <!--Hotel/apartment/hostel/camping details-->
        <hotel>
            <city>Saint-Petersburg</city>
            <!--type-->
            <type>Hotel</type>
            <!--name-->
            <name>Sport</name>
            <!--hotel ranking (stars)-->
            <stars>3</stars>
            <!--type of food-->
            <food>BB</food>
            <!--tv equipment-->
            <tv-equipe>true</tv-equipe>
            <!--air condition equipment-->
            <air-condition>false</air-condition>
            <!--room capacity-->
            <persons>2</persons>
            <!--elevator equipment-->
            <elevator>floor</elevator>
        </hotel>
        <!--Cost per night in US dollars-->
        <cost>50</cost>
    </international-voucher>


    <national-voucher id="1002">
        <voucher-type>excursion</voucher-type>
        <!--<country>Republic_of_Belarus</country>-->
        <number-days-nights>8/7</number-days-nights>
        <transfer>bus</transfer>
        <hotel>
            <city>Braslav</city>
            <type>Village_house</type>
            <name>Borok</name>
            <stars>3</stars>
            <food>FB</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>false</air-condition>
            <persons>6</persons>
            <elevator>no</elevator>
        </hotel>
        <professional-union>true</professional-union>
        <cost>350.00</cost>
    </national-voucher>

    <international-voucher id="1003" country="Bulgari">
        <voucher-type>recreation</voucher-type>
        <number-days-nights>12/11</number-days-nights>
        <transfer>airplane</transfer>
        <hotel>
            <city>Sofia</city>
            <type>Hotel</type>
            <name>Mekka</name>
            <stars>3</stars>
            <food>FB</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>true</air-condition>
            <persons>2</persons>
            <elevator>floor</elevator>
        </hotel>
        <cost>50.45</cost>
    </international-voucher>

    <international-voucher id="1004" country="Russian_Federation">
        <voucher-type>holiday_tour</voucher-type>
        <number-days-nights>3/2</number-days-nights>
        <transfer>train</transfer>
        <hotel>
            <city>Moscow</city>
            <type>Hotel</type>
            <name>Minsk</name>
            <stars>3</stars>
            <food>BB</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>true</air-condition>
            <persons>1</persons>
            <elevator>floor</elevator>
        </hotel>

        <cost>52.65</cost>
    </international-voucher>

    <international-voucher id="1005" country="Italy">
        <voucher-type>recreation</voucher-type>
        <number-days-nights>14/13</number-days-nights>
        <transfer>airplane</transfer>
        <hotel>
            <city>Rome</city>
            <type>Hostel</type>
            <name>Central_Cathedral</name>
            <stars>2</stars>
            <food>RO</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>true</air-condition>
            <persons>2</persons>
            <elevator>no</elevator>
        </hotel>

        <cost>31.56</cost>
    </international-voucher>

    <international-voucher id="1006" country="India">
        <voucher-type>excursion</voucher-type>
        <number-days-nights>31/30</number-days-nights>
        <transfer>airplane</transfer>
        <hotel>
            <city>Deli</city>
            <type>Hotel</type>
            <name>Maharadzha</name>
            <stars>5</stars>
            <food>FB</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>true</air-condition>
            <persons>2</persons>
            <elevator>floor</elevator>
        </hotel>

        <cost>153.56</cost>
    </international-voucher>

    <international-voucher id="1007" country="USA">
        <voucher-type>recreation</voucher-type>
        <number-days-nights>4/3</number-days-nights>
        <transfer>ship</transfer>
        <hotel>
            <city>New_York</city>
            <type>Hotel</type>
            <name>Hilton</name>
            <stars>5</stars>
            <food>FB</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>true</air-condition>
            <persons>2</persons>
            <elevator>penthouse</elevator>
        </hotel>

        <cost>1000.00</cost>
    </international-voucher>

    <international-voucher id="1008" country="Lithuania">
        <voucher-type>holiday_tour</voucher-type>
        <number-days-nights>1/2</number-days-nights>
        <transfer>car</transfer>
        <hotel>
            <city>Vilnius</city>
            <type>Hostel</type>
            <name>Fortuna</name>
            <stars>2</stars>
            <food>RO</food>
            <tv-equipe>false</tv-equipe>
            <air-condition>false</air-condition>
            <persons>8</persons>
            <elevator>no</elevator>
        </hotel>

        <cost>12.22</cost>
    </international-voucher>

    <international-voucher id="1009" country="Republic_Poland">
        <voucher-type>shop_tour</voucher-type>
        <number-days-nights>1/1</number-days-nights>
        <transfer>bus</transfer>
        <hotel>
            <city>Bialostok</city>
            <type>no</type>
            <name>no</name>
            <stars>0</stars>
            <food>RO</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>true</air-condition>
            <persons>54</persons>
            <elevator>no</elevator>
        </hotel>

        <cost>23.45</cost>
    </international-voucher>

    <national-voucher id="1010">
        <voucher-type>holiday_tour</voucher-type>
        <number-days-nights>2/1</number-days-nights>
        <transfer>train</transfer>
        <hotel>
            <city>Minsk</city>
            <type>Hotel</type>
            <name>Minsk</name>
            <stars>5</stars>
            <food>FB</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>true</air-condition>
            <persons>2</persons>
            <elevator>floor</elevator>
        </hotel>
        <professional-union>false</professional-union>

        <cost>200.75</cost>
    </national-voucher>

    <national-voucher id="1011">
        <voucher-type>holiday_tour</voucher-type>
        <number-days-nights>2/1</number-days-nights>
        <transfer>bus</transfer>
        <hotel>
            <city>Grodno</city>
            <type>Hotel</type>
            <name>Belorus'</name>
            <stars>4</stars>
            <food>BB</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>true</air-condition>
            <persons>2</persons>
            <elevator>floor</elevator>
        </hotel>
        <professional-union>true</professional-union>

        <cost>102.45</cost>
    </national-voucher>

    <international-voucher id="1012" country="France">
        <voucher-type>excursion</voucher-type>
        <number-days-nights>7/6</number-days-nights>
        <transfer>airplane</transfer>
        <hotel>
            <city>Paris</city>
            <type>Hotel</type>
            <name>MonMartre</name>
            <stars>3</stars>
            <food>RO</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>false</air-condition>
            <persons>2</persons>
            <elevator>no</elevator>
        </hotel>

        <cost>51.65</cost>
    </international-voucher>

    <international-voucher id="1013" country="Czech_Republic">
        <voucher-type>excursion</voucher-type>
        <number-days-nights>7/6</number-days-nights>
        <transfer>bus</transfer>
        <hotel>
            <city>Prague</city>
            <type>Hotel</type>
            <name>Rapsody</name>
            <stars>3</stars>
            <food>BB</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>false</air-condition>
            <persons>2</persons>
            <elevator>no</elevator>
        </hotel>

        <cost>32.5</cost>
    </international-voucher>

    <international-voucher id="1014" country="USA">
        <voucher-type>ride</voucher-type>
        <number-days-nights>0/1</number-days-nights>
        <transfer>motorcycle</transfer>
        <hotel>
            <city>Brito</city>
            <type>Hotel</type>
            <name>California</name>
            <stars>1</stars>
            <food>RO</food>
            <tv-equipe>true</tv-equipe>
            <air-condition>false</air-condition>
            <persons>2</persons>
            <elevator>no</elevator>
        </hotel>

        <cost>51.15</cost>
    </international-voucher>

    <international-voucher id="1015" country="Saudi_Arabia">
        <voucher-type>hegira</voucher-type>
        <number-days-nights>60/61</number-days-nights>
        <transfer>pedestrian</transfer>
        <hotel>
            <city>Mekka</city>
            <type>Desert/</type>
            <name>Sahara</name>
            <stars>1001</stars>
            <food>RO</food>
            <tv-equipe>false</tv-equipe>
            <air-condition>false</air-condition>
            <persons>1000000</persons>
            <elevator>camel</elevator>
